app = "funpay-cardinal"  # твое имя приложения

[build]
  # Не надо, у нас уже есть requirements.txt

[env]
  FUNPAY_GOLDEN_KEY = "5xsfzthndyfqsg969qlh2ypyq0q2je51"
  TELEGRAM_BOT_TOKEN = "8704132106:AAEujgCsNca1X38bmxRGguVQ4ft4I5ECYgE"
  FPC_IS_RUNNING_ON_RENDER = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = 8080
    
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0
